plugins {
    id 'com.android.application'
}

android {
    namespace "at.amteq.produktion"
    compileSdk 35

    defaultConfig {
        applicationId "at.amteq.produktion"
        minSdk 23
        targetSdk 35
        versionCode 2
        versionName '1.0.1-port5045'
    }
}

dependencies {
    implementation 'androidx.core:core:1.13.1'
}
